In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [2]:
df = pd.read_csv('winequality-red.csv')
df = pd.DataFrame(df)
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [3]:
X = df.drop("quality", axis=1)
y = df["quality"]

In [4]:
standard_scaler = StandardScaler()
X_standardized = standard_scaler.fit_transform(X)
df_standardized = pd.DataFrame(
X_standardized,
columns=X.columns
)
df_standardized.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
0,-0.528360,0.961877,-1.391472,-0.453218,-0.243707,-0.466193,-0.379133,0.558274,1.288643,-0.579207,-0.960246
1,-0.298547,1.967442,-1.391472,0.043416,0.223875,0.872638,0.624363,0.028261,-0.719933,0.128950,-0.584777
2,-0.298547,1.297065,-1.186070,-0.169427,0.096353,-0.083669,0.229047,0.134264,-0.331177,-0.048089,-0.584777
3,1.654856,-1.384443,1.484154,-0.453218,-0.264960,0.107592,0.411500,0.664277,-0.979104,-0.461180,-0.584777
4,-0.528360,0.961877,-1.391472,-0.453218,-0.243707,-0.466193,-0.379133,0.558274,1.288643,-0.579207,-0.960246

In [5]:
minmax_scaler = MinMaxScaler()
X_normalized = minmax_scaler.fit_transform(X)
df_normalized = pd.DataFrame(
X_normalized,
columns=X.columns
)
df_normalized.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
0,0.247788,0.397260,0.00,0.068493,0.106845,0.140845,0.098940,0.567548,0.606299,0.137725,0.153846
1,0.283186,0.520548,0.00,0.116438,0.143573,0.338028,0.215548,0.494126,0.362205,0.209581,0.215385
2,0.283186,0.438356,0.04,0.095890,0.133556,0.197183,0.169611,0.508811,0.409449,0.191617,0.215385
3,0.584071,0.109589,0.56,0.068493,0.105175,0.225352,0.190813,0.582232,0.330709,0.149701,0.215385
4,0.247788,0.397260,0.00,0.068493,0.106845,0.140845,0.098940,0.567548,0.606299,0.137725,0.153846

Exercise 2

In [6]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [7]:
df = pd.read_excel('customer_preprocessing_dataset.xlsx')
print("Original Dataset:")
display(df.head())

Original Dataset:

  Customer_ID   Age  Gender       City  Annual_Income Purchased
0        C001  36.0    Male     Mumbai       452521.0        No
1        C002  47.0    Male     Mumbai       846693.0        No
2        C003  35.0  Female  Hyderabad            NaN       Yes
3        C004  49.0  Female  Bangalore            NaN       Yes
4        C005  30.0  Female     Mumbai            NaN       Yes

In [8]:
# Separate numerical and categorical columns
num_cols = ["Age", "Annual_Income"]
cat_cols = ["Gender", "City", "Purchased"]
# Numerical Imputation (Mean)
num_imputer = SimpleImputer(strategy="mean")
df[num_cols] = num_imputer.fit_transform(df[num_cols])
# Categorical Imputation (Most Frequent)
cat_imputer = SimpleImputer(strategy="most_frequent")
df[cat_cols] = cat_imputer.fit_transform(df[cat_cols])
print("\nDataset after Missing Value Imputation:")
display(df.head())

Dataset after Missing Value Imputation:

  Customer_ID   Age  Gender       City  Annual_Income Purchased
0        C001  36.0    Male     Mumbai  452521.000000        No
1        C002  47.0    Male     Mumbai  846693.000000        No
2        C003  35.0  Female  Hyderabad  631509.653846       Yes
3        C004  49.0  Female  Bangalore  631509.653846       Yes
4        C005  30.0  Female     Mumbai  631509.653846       Yes

In [9]:
label_encoder = LabelEncoder()
df["Purchased"] = label_encoder.fit_transform(df["Purchased"])

In [10]:
df_encoded = pd.get_dummies(
df,
columns=["Gender", "City"],
drop_first=True
)
print("\nDataset after Encoding:")
display(df_encoded.head())

Dataset after Encoding:

,Customer_ID,Age,Annual_Income,Purchased,Gender_Male,City_Chennai,City_Delhi,City_Hyderabad,City_Mumbai
0,C001,36.0,452521.000000,0,True,False,False,False,True
1,C002,47.0,846693.000000,0,True,False,False,False,True
2,C003,35.0,631509.653846,1,False,False,False,True,False
3,C004,49.0,631509.653846,1,False,False,False,False,False
4,C005,30.0,631509.653846,1,False,False,False,False,True

In [11]:
# Separate features and target
X = df_encoded.drop(["Customer_ID", "Purchased"], axis=1)
y = df_encoded["Purchased"]
# Standardization
std_scaler = StandardScaler()
X_standardized = std_scaler.fit_transform(X)
df_standardized = pd.DataFrame(
X_standardized,
columns=X.columns
)
# Normalization
minmax_scaler = MinMaxScaler()
X_normalized = minmax_scaler.fit_transform(X)
df_normalized = pd.DataFrame(
X_normalized,
columns=X.columns
)

In [12]:
print("Standardized Dataset (Mean=0, Std=1):")
display(df_standardized.head())

Standardized Dataset (Mean=0, Std=1):

,Age,Annual_Income,Gender_Male,City_Chennai,City_Delhi,City_Hyderabad,City_Mumbai
0,-0.206645,-1.548986,1.040833,-0.403473,-0.333333,-0.592749,1.779513
1,1.439386,1.862218,1.040833,-0.403473,-0.333333,-0.592749,1.779513
2,-0.356284,0.000000,-0.960769,-0.403473,-0.333333,1.687055,-0.561951
3,1.738665,0.000000,-0.960769,-0.403473,-0.333333,-0.592749,-0.561951
4,-1.104480,0.000000,-0.960769,-0.403473,-0.333333,-0.592749,1.779513

In [13]:
print("Normalized Dataset (Range 0–1):")
display(df_normalized.head())

Normalized Dataset (Range 0–1):

,Age,Annual_Income,Gender_Male,City_Chennai,City_Delhi,City_Hyderabad,City_Mumbai
0,0.433333,0.157710,1.0,0.0,0.0,0.0,1.0
1,0.800000,0.925635,1.0,0.0,0.0,0.0,1.0
2,0.400000,0.506416,0.0,0.0,0.0,1.0,0.0
3,0.866667,0.506416,0.0,0.0,0.0,0.0,0.0
4,0.233333,0.506416,0.0,0.0,0.0,0.0,1.0