In [3]:
import numpy as np
import pandas as pd
from scipy import stats

In [ ]:
Reliance_Data=pd.read_excel('/content/RelianceDataMart.xlsx')
Reliance_Data.head()

   Rice_Bag_Weight
0             24.5
1             24.7
2             25.6
3             25.0
4             24.7

In [ ]:
Reliance_Data.describe()

       Rice_Bag_Weight
count        29.000000
mean         24.446207
std           0.569463
min          23.300000
25%          24.100000
50%          24.500000
75%          24.900000
max          25.600000

In [ ]:
one_sample_result=stats.ttest_1samp(Reliance_Data,25.0)
one_sample_result

TtestResult(statistic=array([-5.23697685]), pvalue=array([1.45121657e-05]), df=array([28]))

H0 (Null Hypothesis) u0 = 25 kg, H1 (Alternative Hyposthesis) u1 = 25 kg \
Hence using one sample T-test we have calculated that T(tab) is less than T(cal) H1 is accepted

In [ ]:
Pre_Post=pd.read_excel('/content/Pre_Post_Score.xlsx')
Pre_Post.head()

   Pre_Score  Post_Score  Diff
0         18          22    -4
1         21          25    -4
2         16          17    -1
3         22          24    -2
4         19          16     3

In [ ]:
Two_sample_result=stats.ttest_rel(Pre_Post['Pre_Score'],Pre_Post['Post_Score'])
Two_sample_result

TtestResult(statistic=np.float64(-3.231252665580312), pvalue=np.float64(0.004394965993185664), df=np.int64(19))

H0 (Null Hypothesis): there is no significance difference between prescore and post score \
H1 (Alternative Hyposthesis) :there is significance difference between prescore and post score \
Hence using two sample Ttest we have calculated that T(tab) is greater than T(cal) H0 is accepted

In [4]:
Crocin=pd.read_excel('/content/Crocin_Data_ST.xlsx')
Crocin.head()

   Before_Crocin  After_Crocin
0          101.0            99
1           99.0            98
2          101.0            97
3           99.9            99
4           99.8            98

In [5]:
Two_sample_result=stats.ttest_rel(Crocin['Before_Crocin'],Crocin['After_Crocin'])
Two_sample_result

TtestResult(statistic=np.float64(7.071712959273876), pvalue=np.float64(1.0800112658101922e-07), df=np.int64(28))

H0 (Null Hypothesis) : there is no significance difference in the templerature before and after taking the crocine \
H1 (Alternative Hyposthesis) : there is significance difference in the templerature before and after taking the crocine \
Hence using two sample T-test we have calculated that T(tab) is smaller than T(cal) H1 is
accepted